#!/usr/bin/env python3
"""
gen_qr.py  –  Generate RGB565 QR-code bitmaps as a C header for TFT_eSPI pushImage().

Usage:
    python3 tools/gen_qr.py

Output:
    src/qr_images.h   (auto-regenerated, do not edit by hand)

Dependencies:
    pip install qrcode[pil] Pillow
"""

import qrcode
from qrcode.image.base import BaseImage
from PIL import Image
import struct, textwrap, pathlib, datetime

# ---------------------------------------------------------------------------
# Configuration – edit URLs / size here
# ---------------------------------------------------------------------------
QR_SPECS = [
    dict(varname="qrFaq",  url="https://hvlp.com/faq",                   size=200),
    dict(varname="qrTech", url="https://hvlp.com/technical-documents/",  size=200),
]

OUT_PATH = pathlib.Path(__file__).parent.parent / "src" / "qr_images.h"

# ---------------------------------------------------------------------------

def make_rgb565(url: str, px_size: int) -> list[int]:
    """Return a flat list of RGB565 uint16 values (row-major) for the QR code."""
    qr = qrcode.QRCode(
        error_correction=qrcode.constants.ERROR_CORRECT_M,
        box_size=1,
        border=4,
    )
    qr.add_data(url)
    qr.make(fit=True)

    # Render as 1-bit image then resize to target pixel size
    img: Image.Image = qr.make_image(fill_color="black", back_color="white").get_image()
    img = img.resize((px_size, px_size), Image.NEAREST).convert("RGB")

    pixels: list[int] = []
    for y in range(img.height):
        for x in range(img.width):
            r, g, b = img.getpixel((x, y))
            rgb565 = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
            pixels.append(rgb565)
    return pixels


def format_array(varname: str, pixels: list[int], width: int, height: int) -> str:
    vals = ", ".join(f"0x{v:04X}" for v in pixels)
    wrapped = textwrap.fill(vals, width=100, subsequent_indent="  ")
    return (
        f"// {varname}: {width}x{height} px\n"
        f"static const uint16_t {varname}[{width * height}] PROGMEM = {{\n"
        f"  {wrapped}\n"
        f"}};\n"
    )


def main():
    guard = "QR_IMAGES_H"
    lines = [
        f"// qr_images.h  –  AUTO-GENERATED by tools/gen_qr.py on {datetime.date.today()}",
        "// Do NOT edit by hand.  Re-run gen_qr.py to regenerate.",
        "",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        "#include <Arduino.h>",
        "",
    ]

    for spec in QR_SPECS:
        print(f"  Generating {spec['varname']}  ({spec['url']}) …")
        pixels = make_rgb565(spec["url"], spec["size"])
        lines.append(format_array(spec["varname"], pixels, spec["size"], spec["size"]))

    lines += [f"#endif // {guard}", ""]

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text("\n".join(lines))
    print(f"  Written → {OUT_PATH}")


if __name__ == "__main__":
    main()
